### ISSUE TITLE
Hello, the posture of your head with only five points is also detected by dwpose, how did you do it

### ISSUE THREAD

**Issue by eightmusic** [bendanzzc/AnimateAnyone-reproduction#10]

**Comment by bendanzzc** [comment]
I use [Open-AnimateAnyone](https://github.com/guoqincode/Open-AnimateAnyone/blob/main/DWPose/dwpose_utils/__init__.py#L27C47-L28C1) to handle, and jus comment the line.

**Comment by eightmusic** [comment]
> I use [Open-AnimateAnyone](https://github.com/guoqincode/Open-AnimateAnyone/blob/main/DWPose/dwpose_utils/__init__.py#L27C47-L28C1) to process pose, and jus comment the line to disable to draw face points

Thanks
