### ISSUE TITLE
Inquiry about Pre-trained Parameter Version for Motion Module and Dataset Size for Training

### ISSUE THREAD

**Issue by liutaocode** [bendanzzc/AnimateAnyone-reproduction#11]
Hello, I would like to ask if you have imported pre-trained parameters for the motion module during your training sessions. Do these pre-trained parameters have a significant impact? If you did import them, could you please specify which version was used - was it v14, v15, or v15_2?

Secondly, how large is the training dataset you utilized? The author mentioned the use of 5,000 videos. With such a limited amount of data, have you encountered any overfitting issues? 

Thank you very much for your response, I look forward to further discussion.

**Comment by bendanzzc** [comment]
I used stable video diffusion(svd) as the pre-train, which is different from animate-anyone, so strictly speaking, it is more like svd-controlnet pipeline. I only used UBC as the dataset.Thanks to the powerful pretrain. I hive not encountered overfitting issues. As for original paper, 5000 **high quality** videos is enough for training with the animatediff pretrain. 5000 video means 10w different images for training in my opinion.

**Comment by liutaocode** [comment]
Thank you for your quick response. 

The github demo you shared is quite impressive, particularly with its temporal consistency. 

The SVD-ControlNet pipeline appears to be a better choice for training human animation models.

In regard to the foundational code used for training your SVD-ControlNet, could you please confirm if the following resource was a reference: https://github.com/CiaraStrawberry/svd-temporal-controlnet?

**Comment by bendanzzc** [comment]
We just borrowed their inference code, and we do not plan to open source the training code. However, we guess that their code can also be used for training.

**Comment by liutaocode** [comment]
Thanks. I will continue to follow this repository and appreciate your contribution to the open-source community.
