### ISSUE TITLE
good proj, i run this v1 version on my 2080ti computer, takes very long time and the results(the video below) are not good( gestures barely moves). wish you can make it better. 

### ISSUE THREAD

**Issue by linruier** [bendanzzc/AnimateAnyone-reproduction#12]
https://github.com/bendanzzc/AnimateAnyone-reproduction/assets/25625954/acc04014-67e8-4d12-955a-7bc55bd49b68

**Comment by bendanzzc** [comment]
Thank you for your attention, but there seems to be a problem with the video playback. From your description, it is speculated that it may be necessary to use your dataset for fine-tuning. If you have any questions, feel free to communicate on GitHub or WeChat group.
