### ISSUE TITLE
Cannot import name 'UNetMidBlockSpatioTemporal' from 'diffusers.models.unet_3d_blocks'

### ISSUE THREAD

**Issue by Valentino-L** [bendanzzc/AnimateAnyone-reproduction#13]
Hi! I'm having this import problem when trying to run the code. How could I solve it? I install all requirements from [svd-temporal-controlnet](https://github.com/CiaraStrawberry/svd-temporal-controlnet). Maybe there is a specific version of diffusers I need to use? I'm using torch 2.0.1 as required by svd

Thanks a lot!

<img width="869" alt="Screenshot 2024-02-25 at 21 24 15" src="https://github.com/bendanzzc/AnimateAnyone-reproduction/assets/67510831/286ff49a-8773-484c-a96c-1838fff3ab7c">

**Comment by bendanzzc** [comment]
May be  `pip install diffusers==0.25.0` can help
