### ISSUE TITLE
from utils.scheduling_euler_discrete_karras_fix import EulerDiscreteScheduler: do not have scheduling_euler_discrete_karras_fix !

### ISSUE THREAD

**Issue by goalslee** [bendanzzc/AnimateAnyone-reproduction#14]
pipeline_stable_video_diffusion_controlnet_long.py #31 from utils.scheduling_euler_discrete_karras_fix import EulerDiscreteScheduler . do not have scheduling_euler_discrete_karras_fix file

**Comment by bendanzzc** [comment]
[fix](https://github.com/bendanzzc/AnimateAnyone-reproduction/blob/main/pipeline_stable_video_diffusion_controlnet_long.py#L31)
