### ISSUE TITLE
how to get my own dwpose like testcase?thank you!

### ISSUE THREAD

**Issue by goalslee** [bendanzzc/AnimateAnyone-reproduction#18]
![1](https://github.com/bendanzzc/AnimateAnyone-reproduction/assets/9686504/ff7dbb26-26ea-46d5-bcad-6109666e7c3c)

like this one

**Comment by bendanzzc** [comment]
please refer [open-animateanyone](https://github.com/guoqincode/Open-AnimateAnyone/tree/main/DWPose)
