### ISSUE TITLE
Release Code

### ISSUE THREAD

**Issue by ChaunceyWang** [bendanzzc/AnimateAnyone-reproduction#2]
I have  two questions:
1.  Is the video given by trainning the stage 2? (or without stage 2),   using temporal layer in animatediff?
because many developers report stage2 is difficult to train.

2. can you release the current code next week？

**Comment by bendanzzc** [comment]
1. our result is based on stable video diffusion with DWpose condition. the pipeline is more like video T2i-adapter or video controlNet rather than animate anyone.
2. We will release the code as soon as possible
