### ISSUE TITLE
facial enhancement

### ISSUE THREAD

**Issue by wangxr1999** [bendanzzc/AnimateAnyone-reproduction#3]
Hello, very good results, may I ask how facial enhancement is achieved？

**Comment by bendanzzc** [comment]
不对论文做评价，只是通过通义千问的case来看，是后期视频换脸达到的，极端case下可以看到通义千问的case的脸有明显断层，和视频换脸的表现很像，当然只是推测，至少这条路落地是通的，当然对学术研究没啥用
