### ISSUE TITLE
I salute your open source spirit and hope to release some code first.

### ISSUE THREAD

**Issue by rwywenyi** [bendanzzc/AnimateAnyone-reproduction#4]
Hello, I'm thrilled to hear that you're about to release the code! I'm eagerly looking forward to it.

I salute your open source spirit and hope to release some code first.

**Comment by bendanzzc** [comment]
OK, I will release inference code by next week, which is not well organized but works

**Comment by rwywenyi** [comment]
The earth and the sky will praise your generosity, and countless algorithm engineers will praise you, the selfless devotee, the great architect.
