### ISSUE TITLE
svd unet training

### ISSUE THREAD

**Issue by jiangzhengkai** [bendanzzc/AnimateAnyone-reproduction#6]
Hi, thanks for sharing your fashion results based SVD, i want to know whether you train all unet parameters on UBC datasets? If so, how about your training resolution.

**Comment by bendanzzc** [comment]
we train all unet parameters on UBC and the training resolution is as large as possible depending on GPU

**Comment by Yanting-K** [comment]
svd's unet and controlnet joinin training?

**Comment by bendanzzc** [comment]
yes
