### ISSUE TITLE
Possibilities for collaboration?

### ISSUE THREAD

**Issue by Valentino-L** [bendanzzc/AnimateAnyone-reproduction#8]
Hi! We are very interested in your version of reproduction of AnimateAnyone. Are you open to discuss business collaboration possibilities? Would it be possible to share your email address or other contact details?

Many thanks!

**Comment by bendanzzc** [comment]
Thank you for your interest in our project. We are honored that someone is interested in our work. However, we currently have no plans to commercialize it. We will release primary checkpoint, and anyone can finetune it. We hope that our work can make a certain contribution to the community.

Many thanks!

**Comment by Valentino-L** [comment]
For sure we absolutely understand. We are not asking for you to commercialise this particular source code at all, we are only looking for relevant talents who can help us develop our own technologies. If you interested to be hired for technical development for other projects, don’t hesitate to let us know.

**Comment by bendanzzc** [comment]
Sorry for the misunderstanding. I am interested in learning more, and you can contact me via email(bendanzzc@qq.com) at any time.
