### ISSUE TITLE
Long-range frames generation

### ISSUE THREAD

**Issue by jiangzhengkai** [bendanzzc/AnimateAnyone-reproduction#9]
Hi, I want know how you handle long-range frames generation based on SVD. Do you use first frame as ref image or just random select from the whole video?

**Comment by jiangzhengkai** [comment]
@bendanzzc You discard the first frame result in your ppl? Why not use 13 frames results instead of 14 frames in total

**Comment by bendanzzc** [comment]
I random select ref image from the same video to break the law that svd use ref-image to generate first frame.

In principle, I would use 14 frames, but there may be bugs in the pipeline, and I will check it.  So far, the results seem to be normal.

**Comment by jiangzhengkai** [comment]
@bendanzzc Thanks for your reply. I have trained both unet and controlnet on fashion dataset by random selecting ref image and using long-range generation ppl. however, the results are not good especially for appearance.

https://github.com/bendanzzc/AnimateAnyone-reproduction/assets/19780166/d3341494-940c-41cc-86b3-a9a8db4a1bc4

**Comment by jiangzhengkai** [comment]
training resolution is 512x512 and I train 50k steps in total.

**Comment by jiangzhengkai** [comment]
@bendanzzc You keep the original aspect ratio during training?

**Comment by bendanzzc** [comment]
Yes, just like the size in inference code, but I am not sure that is the key point. Or you can train origin SVD-controlnet which like V0.9, if everyting is ok ,it will converge very fast

**Comment by jiangzhengkai** [comment]
@bendanzzc In your V0.9, you use the first frame as ref frame? And about dataset, do you use the original resize implemenation or your own ratio-keep implementation?

**Comment by bendanzzc** [comment]
yes, in v0.9, I use first frame as ref image, and I use ratio-keep implementation, and only train controlnet for a day with 2 GPUs

**Comment by bendanzzc** [comment]
like origin svd, only can inference 14 frames pre ref-image, so it can not generate complete video from a single ref-image

**Comment by jiangzhengkai** [comment]
@bendanzzc Above video results are 256x256 training setting. Have you compare different resolutions?

**Comment by bendanzzc** [comment]
yes, all resolutions I tested are all bigger than 512, and keep the ratio of video. bigger resolution benefits human face or other small textures to some extents.

**Comment by jiangzhengkai** [comment]
@bendanzzc How abount training resolution?

**Comment by bendanzzc** [comment]
same as the size in inference code or bigger. there is no much different

**Comment by jiangzhengkai** [comment]
https://github.com/bendanzzc/AnimateAnyone-reproduction/assets/19780166/c5f2ebe4-26f3-429e-9987-8ef4fe73d6e4

training resolution is very important for SVD, especially for human face.

**Comment by bendanzzc** [comment]
If you have better result, welcome to share to let us konw the advanced results

**Comment by jiangzhengkai** [comment]
https://github.com/bendanzzc/AnimateAnyone-reproduction/assets/19780166/f34e546e-4fd9-4243-8ba9-e2374b9c5275

Update results on different poses. Maybe Controlnet should be the reference net like animate anyaone, cause pose is easy to control. Only image latent for appearance is not enough.

**Comment by bendanzzc** [comment]
the result looks cool!

Your idea makes sense! In my opinion the controlnet already has an input of ref-image, which supports plus opeartion for unet and Unet itself has ref-image as well. I feel that it may to some extent achieve the reference function. I also feel that the data quailty and quantity are also a part of the reason. I am not sure and may be the experimental results matters.

If you have any new progress, welcome to share and let me learn advanced research.
